name: fedora-milana
base-image: quay.io/fedora-ostree-desktops/sericea
fedora-version: 38 # latest can also be used
description: My own fedora silverblue build with sway - the way I want it

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - python3-pip
  - libadwaita
  - mako
  - flatpak
  - git
  - wofi
  - fish
  - distrobox
  - podman
  - rcm
  - grim
  - slurp
  - udiskie
  - lxpolkit
  - emacs
  - neovim
  - ark
  - android-tools
  - gvfs
  - gvfs-mtp

