name: fedora-milana
base-image: quay.io/fedora-ostree-desktops/sericea
fedora-version: 38 # latest can also be used
description: My own fedora silverblue build with sway - the way I want it

rpm:
  repos:
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
  install:
    - python3-pip
    - libadwaita
    - mako
    - flatpak
    - git
    - wofi
    - fish
    - distrobox
    - podman
    - rcm
    - grim
    - slurp
    - udiskie
    - lxpolkit
    - emacs
    - neovim
    - ark
    - android-tools
    - gvfs
    - gvfs-mtp
  remove:
    - firefox
    - firefox-langpacks
    - rofi-wayland
    - rofi-themes
    - virtualbox-guest-additions
    - dunst

firstboot:
  yafti: true

